name: User Story Proposal
description: |
  Use this template to provide a User Story for a WoT requirement,
  connecting motivating use cases to features.
labels: ["US"]
title: "Provide a concise title for your user story (will be used to form an id)."
body:
  - type: markdown
    attributes:
      value: |
        > [!Note]
        Thank you for proposing a new user story to capture high-level requirements for WoT features!
        User story proposals use a structured GitHub issue so that we can semi-automate the process.
        User stories follow the format of "As a (WHO), I need (WHAT) so that I can (WHY)", but we will prompt
        for each of WHO, WHAT, and WHY separately.   See the document for examples.
        A bot will check the suggestion after creation, and report on missing properties or other problems
        before we review the suggestion.
  - type: input
    id: submitter
    attributes:
      label: Submitter Contact Information
      description: |
        Please enter your desired form of contact (e.g. email or GitHub account name).
        Write "Separate" if you want to provide this in another way.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Who (As a...)
  - type: input
    id: who
    attributes:
      label: Main Stakeholder (As a...)
      description: |
        The stakeholder who would benefit from or needs the feature.
        This may be an organization, such as an SDO, or a user role, such as a system owner or TD developer.
        The stakeholder and the submitter may be distinct or the same.
    validations:
      required: true
  - type: textarea
    id: who-others
    attributes:
      label: Other Stakeholders
      description: |
          Other stakeholders that may be impacted.  Use a markdown list, with one stakeholder per line,
          providing definitions in the Details field if necessary.
      render: markdown
    validations:
      required: false
  - type: textarea
    id: who-details
    attributes:
      label: Stakeholder Details
      description: |
          Additional information on the stakeholders, if required.
          If any stakeholder is not one already defined in the document, propose a definition (if a user role)
          or a link (if an organization, such as an SDO).
      render: markdown
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## What (I need...)
  - type: input
    id: what
    attributes:
      label: Capability (I need...)
      description: |
        What is the desired capability, capacity, or feature?  Provide a short
        summary suitable for inclusion in a user story sentence.  This should be a single
        noun phrase.  If multiple, distinct capabilities are needed to satisfy a single
        purpose consider proposing multiple user stories.
    validations:
      required: true
  - type: textarea
    id: what-details
    attributes:
      label: Capability Details
      description: |
         Link to existing features (e.g. sets of assertions) in published WoT standards if the
         capability already exists (if you are documenting the requirements for an existing feature)
         or link to an issue or MD file describing the technical details for a feature if the
         feature does not yet exist but is to be proposed.
      render: markdown
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Why (so that I can...)
  - type: input
    id: why
    attributes:
      label: Purpose (so that I can...)
      description: |
        Provide a simple verb phrase summarizing the purpose of the requested feature.
    validations:
      required: true
  - type: textarea
    id: why-details
    attributes:
      label: Purpose Details
      description: |
        Any additional details needed to better explain the purpose of the
        proposed capability.  If there are multiple reasons for a particular
        capability provide them as a list.
      render: markdown
    validations:
      required: false
  - type: textarea
    id: why-motivation
    attributes:
      label: Purpose Motivation
      description: |
        Provide links to one or more motivating Use Cases or Use Case Categories.
        If a new Use Case or Use Case Category is needed submit separate issues
        and link to these issues, otherwise link to corresponding sections in the document.
      render: markdown
    validations:
      required: true

  
